[2019-12-03 22:59:41] [INFO] [MainThread] [handlers.py:63] Request Infomations:
+-----Headers-----+
| Host            | 127.0.0.1:8084  
| Connection      | keep-alive      
| Access-Control-Request-Method | GET             
| Origin          | http://localhost:8080 
| User-Agent      | Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36 
| Access-Control-Request-Headers | authorization   
| Accept          | */*             
| Sec-Fetch-Site  | cross-site      
| Sec-Fetch-Mode  | cors            
| Referer         | http://localhost:8080/interfacesManage 
| Accept-Encoding | gzip, deflate, br 
| Accept-Language | zh-CN,zh;q=0.9  

[2019-12-03 22:59:41] [INFO] [MainThread] [handlers.py:44] Response Infomations:
+-----Headers-----+
| Content-Type    | application/json 

Body:
| DbSettingHandler object has list index out of range
[2019-12-03 22:59:41] [INFO] [MainThread] [handlers.py:63] Request Infomations:
+-----Headers-----+
| Host            | 127.0.0.1:8084  
| Connection      | keep-alive      
| Access-Control-Request-Method | GET             
| Origin          | http://localhost:8080 
| User-Agent      | Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36 
| Access-Control-Request-Headers | authorization   
| Accept          | */*             
| Sec-Fetch-Site  | cross-site      
| Sec-Fetch-Mode  | cors            
| Referer         | http://localhost:8080/interfacesManage 
| Accept-Encoding | gzip, deflate, br 
| Accept-Language | zh-CN,zh;q=0.9  

[2019-12-03 22:59:41] [INFO] [MainThread] [handlers.py:44] Response Infomations:
+-----Headers-----+
| Content-Type    | application/json 

Body:
| DbSettingHandler object has list index out of range
[2019-12-03 22:59:41] [INFO] [MainThread] [handlers.py:63] Request Infomations:
+-----Headers-----+
| Host            | 127.0.0.1:8084  
| Connection      | keep-alive      
| Accept          | application/json, text/plain, */* 
| Origin          | http://localhost:8080 
| Authorization   | eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmlja19uYW1lIjpudWxsLCJleHAiOjE1NzUwMjI1MzJ9.pTzgTRDJHyQfEiLyRTxhcDf10FBCvG0_eyP1Wv0pPzY 
| User-Agent      | Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36 
| Sec-Fetch-Site  | cross-site      
| Sec-Fetch-Mode  | cors            
| Referer         | http://localhost:8080/interfacesManage 
| Accept-Encoding | gzip, deflate, br 
| Accept-Language | zh-CN,zh;q=0.9  
| If-None-Match   | "967b4b0cf9ca98f1ba07b0118cb4ed541da3c410" 

[2019-12-03 22:59:41] [INFO] [MainThread] [handlers.py:44] Response Infomations:
+-----Headers-----+
| Content-Type    | application/json 

Body:
| {
|     "code": 1,
|     "msg": "数据库配置数据查询成功!",
|     "data": [
|         {
|             "id": 2,
|             "add_time": "2019-11-27T18:02:58",
|             "name": "3131",
|             "creator": {
|                 "id": 1,
|                 "add_time": "2019-12-03T22:59:41.318205",
|                 "account": null,
|                 "password": null,
|                 "nick_name": null,
|                 "head_url": null,
|                 "address": null,
|                 "desc": null,
|                 "gender": null
|             },
|             "db_type": "313",
|             "db_user": "31",
|             "db_password": "31",
|             "db_host": "31",
|             "db_port": 31,
|             "desc": "31"
|         }
|     ]
| }
[2019-12-03 22:59:41] [INFO] [MainThread] [handlers.py:63] Request Infomations:
+-----Headers-----+
| Host            | 127.0.0.1:8084  
| Connection      | keep-alive      
| Accept          | application/json, text/plain, */* 
| Origin          | http://localhost:8080 
| Authorization   | eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmlja19uYW1lIjpudWxsLCJleHAiOjE1NzUwMjI1MzJ9.pTzgTRDJHyQfEiLyRTxhcDf10FBCvG0_eyP1Wv0pPzY 
| User-Agent      | Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36 
| Sec-Fetch-Site  | cross-site      
| Sec-Fetch-Mode  | cors            
| Referer         | http://localhost:8080/interfacesManage 
| Accept-Encoding | gzip, deflate, br 
| Accept-Language | zh-CN,zh;q=0.9  
| If-None-Match   | "c5c0f141aa44f848bcd669ba5dfd53856d4282e1" 

[2019-12-03 22:59:41] [INFO] [MainThread] [handlers.py:44] Response Infomations:
+-----Headers-----+
| Content-Type    | application/json 

Body:
| {
|     "code": 1,
|     "msg": "数据库配置数据查询成功!",
|     "data": [
|         {
|             "id": 2,
|             "add_time": "2019-11-27T18:02:58",
|             "name": "3131",
|             "creator": {
|                 "id": 1,
|                 "add_time": "2019-12-03T22:59:41.370288",
|                 "account": null,
|                 "password": null,
|                 "nick_name": null,
|                 "head_url": null,
|                 "address": null,
|                 "desc": null,
|                 "gender": null
|             },
|             "db_type": "313",
|             "db_user": "31",
|             "db_password": "31",
|             "db_host": "31",
|             "db_port": 31,
|             "desc": "31"
|         }
|     ]
| }
[2019-12-03 22:59:43] [INFO] [MainThread] [handlers.py:63] Request Infomations:
+-----Headers-----+
| Host            | 127.0.0.1:8084  
| Connection      | keep-alive      
| Access-Control-Request-Method | GET             
| Origin          | http://localhost:8080 
| User-Agent      | Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36 
| Access-Control-Request-Headers | authorization   
| Accept          | */*             
| Sec-Fetch-Site  | cross-site      
| Sec-Fetch-Mode  | cors            
| Referer         | http://localhost:8080/interfacesManage 
| Accept-Encoding | gzip, deflate, br 
| Accept-Language | zh-CN,zh;q=0.9  

[2019-12-03 22:59:43] [INFO] [MainThread] [handlers.py:44] Response Infomations:
+-----Headers-----+
| Content-Type    | application/json 

Body:
| ProjectHandler object has list index out of range
[2019-12-03 22:59:43] [INFO] [MainThread] [handlers.py:63] Request Infomations:
+-----Headers-----+
| Host            | 127.0.0.1:8084  
| Connection      | keep-alive      
| Accept          | application/json, text/plain, */* 
| Origin          | http://localhost:8080 
| Authorization   | eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmlja19uYW1lIjpudWxsLCJleHAiOjE1NzUwMjI1MzJ9.pTzgTRDJHyQfEiLyRTxhcDf10FBCvG0_eyP1Wv0pPzY 
| User-Agent      | Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36 
| Sec-Fetch-Site  | cross-site      
| Sec-Fetch-Mode  | cors            
| Referer         | http://localhost:8080/interfacesManage 
| Accept-Encoding | gzip, deflate, br 
| Accept-Language | zh-CN,zh;q=0.9  
| If-None-Match   | "44682404f99fe1328310d8a34853d819b94d6048" 

[2019-12-03 22:59:43] [INFO] [MainThread] [handlers.py:44] Response Infomations:
+-----Headers-----+
| Content-Type    | application/json 

Body:
| {
|     "code": 1,
|     "msg": "项目数据查询成功!",
|     "data": [
|         {
|             "id": 6,
|             "add_time": "2019-12-02T21:50:07",
|             "name": "生产",
|             "env": {
|                 "id": 9,
|                 "add_time": "2019-12-03T22:59:43.310302",
|                 "name": "生产",
|                 "creator": null,
|                 "host_address": "https://app30.aotuzuche.com:7065",
|                 "desc": null
|             },
|             "creator": {
|                 "id": 1,
|                 "add_time": "2019-12-03T22:59:43.310302",
|                 "account": null,
|                 "password": null,
|                 "nick_name": null,
|                 "head_url": null,
|                 "address": null,
|                 "desc": null,
|                 "gender": null
|             },
|             "desc": "12313"
|         },
|         {
|             "id": 5,
|             "add_time": "2019-11-27T16:41:03",
|             "name": "踩踩踩踩踩",
|             "env": {
|                 "id": 8,
|                 "add_time": "2019-12-03T22:59:43.310827",
|                 "name": "谢谢谢谢",
|                 "creator": null,
|                 "host_address": "https://testapp.atzuche.com:7065",
|                 "desc": null
|             },
|             "creator": {
|                 "id": 1,
|                 "add_time": "2019-12-03T22:59:43.310827",
|                 "account": null,
|                 "password": null,
|                 "nick_name": null,
|                 "head_url": null,
|                 "address": null,
|                 "desc": null,
|                 "gender": null
|             },
|             "desc": "23213"
|         },
|         {
|             "id": 4,
|             "add_time": "2019-11-27T16:18:15",
|             "name": "测试",
|             "env": {
|                 "id": 7,
|                 "add_time": "2019-12-03T22:59:43.311294",
|                 "name": "测试",
|                 "creator": null,
|                 "host_address": "http://127.0.0.1:8084",
|                 "desc": null
|             },
|             "creator": {
|                 "id": 1,
|                 "add_time": "2019-12-03T22:59:43.311294",
|                 "account": null,
|                 "password": null,
|                 "nick_name": null,
|                 "head_url": null,
|                 "address": null,
|                 "desc": null,
|                 "gender": null
|             },
|             "desc": "1其"
|         },
|         {
|             "id": 3,
|             "add_time": "2019-11-27T16:06:23",
|             "name": "嘻嘻嘻",
|             "env": {
|                 "id": 6,
|                 "add_time": "2019-12-03T22:59:43.311294",
|                 "name": "休息休息",
|                 "creator": null,
|                 "host_address": "xxxx",
|                 "desc": null
|             },
|             "creator": {
|                 "id": 1,
|                 "add_time": "2019-12-03T22:59:43.311294",
|                 "account": null,
|                 "password": null,
|                 "nick_name": null,
|                 "head_url": null,
|                 "address": null,
|                 "desc": null,
|                 "gender": null
|             },
|             "desc": "嘻嘻嘻"
|         },
|         {
|             "id": 2,
|             "add_time": "2019-11-27T15:50:44",
|             "name": "e31231",
|             "env": {
|                 "id": 4,
|                 "add_time": "2019-12-03T22:59:43.311294",
|                 "name": "made打打",
|                 "creator": null,
|                 "host_address": "eqeq",
|                 "desc": null
|             },
|             "creator": {
|                 "id": 1,
|                 "add_time": "2019-12-03T22:59:43.311294",
|                 "account": null,
|                 "password": null,
|                 "nick_name": null,
|                 "head_url": null,
|                 "address": null,
|                 "desc": null,
|                 "gender": null
|             },
|             "desc": "3131"
|         },
|         {
|             "id": 1,
|             "add_time": "2019-11-27T15:44:52",
|             "name": "3131",
|             "env": {
|                 "id": 5,
|                 "add_time": "2019-12-03T22:59:43.311790",
|                 "name": "远远",
|                 "creator": null,
|                 "host_address": "31",
|                 "desc": null
|             },
|             "creator": {
|                 "id": 1,
|                 "add_time": "2019-12-03T22:59:43.311790",
|                 "account": null,
|                 "password": null,
|                 "nick_name": null,
|                 "head_url": null,
|                 "address": null,
|                 "desc": null,
|                 "gender": null
|             },
|             "desc": "1231"
|         }
|     ]
| }
[2019-12-03 22:59:56] [INFO] [MainThread] [handlers.py:63] Request Infomations:
+-----Headers-----+
| Host            | 127.0.0.1:8084  
| Connection      | keep-alive      
| Access-Control-Request-Method | POST            
| Origin          | http://localhost:8080 
| User-Agent      | Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36 
| Access-Control-Request-Headers | authorization,content-type 
| Accept          | */*             
| Sec-Fetch-Site  | cross-site      
| Sec-Fetch-Mode  | cors            
| Referer         | http://localhost:8080/interfacesManage 
| Accept-Encoding | gzip, deflate, br 
| Accept-Language | zh-CN,zh;q=0.9  

[2019-12-03 22:59:56] [INFO] [MainThread] [handlers.py:44] Response Infomations:
+-----Headers-----+
| Content-Type    | application/json 

Body:
| InterfacesDebugHandler object has list index out of range
[2019-12-03 22:59:56] [INFO] [MainThread] [handlers.py:63] Request Infomations:
+-----Headers-----+
| Host            | 127.0.0.1:8084  
| Connection      | keep-alive      
| Content-Length  | 113             
| Accept          | application/json, text/plain, */* 
| Origin          | http://localhost:8080 
| Authorization   | eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmlja19uYW1lIjpudWxsLCJleHAiOjE1NzUwMjI1MzJ9.pTzgTRDJHyQfEiLyRTxhcDf10FBCvG0_eyP1Wv0pPzY 
| User-Agent      | Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36 
| Content-Type    | application/json;charset=UTF-8 
| Sec-Fetch-Site  | cross-site      
| Sec-Fetch-Mode  | cors            
| Referer         | http://localhost:8080/interfacesManage 
| Accept-Encoding | gzip, deflate, br 
| Accept-Language | zh-CN,zh;q=0.9  
+----Arguments----+
| 'url'           | 'http://114.55.235.185:9031/autoyolConsole/main' 
| 'method'        | 'POST'          
| 'headers'       | '{}'            
| 'params'        | '{}'            
| 'project'       | 5               

[2019-12-03 23:00:17] [ERROR] [MainThread] [handlers.py:105] Uncaught exception POST /interfaces_debug/ (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8084', method='POST', uri='/interfaces_debug/', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\urllib3\util\connection.py", line 80, in create_connection
    raise err
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\urllib3\util\connection.py", line 70, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\urllib3\connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\http\client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\http\client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\http\client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\http\client.py", line 966, in send
    self.connect()
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\urllib3\connection.py", line 181, in connect
    conn = self._new_conn()
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\urllib3\connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001F0736EA308>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\urllib3\util\retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='114.55.235.185', port=9031): Max retries exceeded with url: /autoyolConsole/main (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F0736EA308>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\tornado\web.py", line 1699, in _execute
    result = await result
  File "F:\MagicTestPlatform\apps\utils\wrappers.py", line 25, in wrapper
    await method(self, *args, **kwargs)
  File "F:\MagicTestPlatform\apps\interface_test\handlers.py", line 79, in post
    response = http_client.make_test_templates()
  File "F:\MagicTestPlatform\apps\utils\http_keywords.py", line 76, in make_test_templates
    response = self.post(**request_body)
  File "F:\MagicTestPlatform\apps\utils\http_keywords.py", line 27, in post
    return requests.post(verify=False, **kwargs)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\requests\api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='114.55.235.185', port=9031): Max retries exceeded with url: /autoyolConsole/main (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F0736EA308>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
[2019-12-03 23:00:17] [INFO] [MainThread] [handlers.py:44] Response Infomations:
+-----Headers-----+
| Content-Type    | text/plain      

Body:
| Traceback (most recent call last):
| 
[2019-12-03 23:00:17] [INFO] [MainThread] [handlers.py:63] Request Infomations:
+-----Headers-----+
| Host            | 127.0.0.1:8084  
| Connection      | keep-alive      
| Content-Length  | 113             
| Accept          | application/json, text/plain, */* 
| Origin          | http://localhost:8080 
| Authorization   | eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmlja19uYW1lIjpudWxsLCJleHAiOjE1NzUwMjI1MzJ9.pTzgTRDJHyQfEiLyRTxhcDf10FBCvG0_eyP1Wv0pPzY 
| User-Agent      | Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36 
| Content-Type    | application/json;charset=UTF-8 
| Sec-Fetch-Site  | cross-site      
| Sec-Fetch-Mode  | cors            
| Referer         | http://localhost:8080/interfacesManage 
| Accept-Encoding | gzip, deflate, br 
| Accept-Language | zh-CN,zh;q=0.9  
+----Arguments----+
| 'url'           | 'http://114.55.235.185:9031/autoyolConsole/main' 
| 'method'        | 'POST'          
| 'headers'       | '{}'            
| 'params'        | '{}'            
| 'project'       | 5               

[2019-12-03 23:00:17] [INFO] [MainThread] [handlers.py:63] Request Infomations:
+-----Headers-----+
| Host            | 127.0.0.1:8084  
| Connection      | keep-alive      
| Content-Length  | 113             
| Accept          | application/json, text/plain, */* 
| Origin          | http://localhost:8080 
| Authorization   | eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmlja19uYW1lIjpudWxsLCJleHAiOjE1NzUwMjI1MzJ9.pTzgTRDJHyQfEiLyRTxhcDf10FBCvG0_eyP1Wv0pPzY 
| User-Agent      | Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36 
| Content-Type    | application/json;charset=UTF-8 
| Sec-Fetch-Site  | cross-site      
| Sec-Fetch-Mode  | cors            
| Referer         | http://localhost:8080/interfacesManage 
| Accept-Encoding | gzip, deflate, br 
| Accept-Language | zh-CN,zh;q=0.9  
+----Arguments----+
| 'url'           | 'http://114.55.235.185:9031/autoyolConsole/main' 
| 'method'        | 'POST'          
| 'headers'       | '{}'            
| 'params'        | '{}'            
| 'project'       | 5               

[2019-12-03 23:00:17] [INFO] [MainThread] [handlers.py:63] Request Infomations:
+-----Headers-----+
| Host            | 127.0.0.1:8084  
| Connection      | keep-alive      
| Content-Length  | 113             
| Accept          | application/json, text/plain, */* 
| Origin          | http://localhost:8080 
| Authorization   | eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmlja19uYW1lIjpudWxsLCJleHAiOjE1NzUwMjI1MzJ9.pTzgTRDJHyQfEiLyRTxhcDf10FBCvG0_eyP1Wv0pPzY 
| User-Agent      | Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36 
| Content-Type    | application/json;charset=UTF-8 
| Sec-Fetch-Site  | cross-site      
| Sec-Fetch-Mode  | cors            
| Referer         | http://localhost:8080/interfacesManage 
| Accept-Encoding | gzip, deflate, br 
| Accept-Language | zh-CN,zh;q=0.9  
+----Arguments----+
| 'url'           | 'http://114.55.235.185:9031/autoyolConsole/main' 
| 'method'        | 'POST'          
| 'headers'       | '{}'            
| 'params'        | '{}'            
| 'project'       | 5               

[2019-12-03 23:00:17] [INFO] [MainThread] [handlers.py:63] Request Infomations:
+-----Headers-----+
| Host            | 127.0.0.1:8084  
| Connection      | keep-alive      
| Content-Length  | 113             
| Accept          | application/json, text/plain, */* 
| Origin          | http://localhost:8080 
| Authorization   | eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmlja19uYW1lIjpudWxsLCJleHAiOjE1NzUwMjI1MzJ9.pTzgTRDJHyQfEiLyRTxhcDf10FBCvG0_eyP1Wv0pPzY 
| User-Agent      | Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36 
| Content-Type    | application/json;charset=UTF-8 
| Sec-Fetch-Site  | cross-site      
| Sec-Fetch-Mode  | cors            
| Referer         | http://localhost:8080/interfacesManage 
| Accept-Encoding | gzip, deflate, br 
| Accept-Language | zh-CN,zh;q=0.9  
+----Arguments----+
| 'url'           | 'http://114.55.235.185:9031/autoyolConsole/main' 
| 'method'        | 'POST'          
| 'headers'       | '{}'            
| 'params'        | '{}'            
| 'project'       | 5               

[2019-12-03 23:00:17] [INFO] [MainThread] [handlers.py:63] Request Infomations:
+-----Headers-----+
| Host            | 127.0.0.1:8084  
| Connection      | keep-alive      
| Content-Length  | 113             
| Accept          | application/json, text/plain, */* 
| Origin          | http://localhost:8080 
| Authorization   | eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmlja19uYW1lIjpudWxsLCJleHAiOjE1NzUwMjI1MzJ9.pTzgTRDJHyQfEiLyRTxhcDf10FBCvG0_eyP1Wv0pPzY 
| User-Agent      | Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36 
| Content-Type    | application/json;charset=UTF-8 
| Sec-Fetch-Site  | cross-site      
| Sec-Fetch-Mode  | cors            
| Referer         | http://localhost:8080/interfacesManage 
| Accept-Encoding | gzip, deflate, br 
| Accept-Language | zh-CN,zh;q=0.9  
+----Arguments----+
| 'url'           | 'http://114.55.235.185:9031/autoyolConsole/main' 
| 'method'        | 'POST'          
| 'headers'       | '{}'            
| 'params'        | '{}'            
| 'project'       | 5               

[2019-12-03 23:00:17] [INFO] [MainThread] [handlers.py:63] Request Infomations:
+-----Headers-----+
| Host            | 127.0.0.1:8084  
| Connection      | keep-alive      
| Content-Length  | 113             
| Accept          | application/json, text/plain, */* 
| Origin          | http://localhost:8080 
| Authorization   | eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmlja19uYW1lIjpudWxsLCJleHAiOjE1NzUwMjI1MzJ9.pTzgTRDJHyQfEiLyRTxhcDf10FBCvG0_eyP1Wv0pPzY 
| User-Agent      | Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36 
| Content-Type    | application/json;charset=UTF-8 
| Sec-Fetch-Site  | cross-site      
| Sec-Fetch-Mode  | cors            
| Referer         | http://localhost:8080/interfacesManage 
| Accept-Encoding | gzip, deflate, br 
| Accept-Language | zh-CN,zh;q=0.9  
+----Arguments----+
| 'url'           | 'http://114.55.235.185:9031/autoyolConsole/main' 
| 'method'        | 'POST'          
| 'headers'       | '{}'            
| 'params'        | '{}'            
| 'project'       | 5               

[2019-12-03 23:00:39] [ERROR] [MainThread] [handlers.py:105] Uncaught exception POST /interfaces_debug/ (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8084', method='POST', uri='/interfaces_debug/', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\urllib3\util\connection.py", line 80, in create_connection
    raise err
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\urllib3\util\connection.py", line 70, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\urllib3\connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\http\client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\http\client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\http\client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\http\client.py", line 966, in send
    self.connect()
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\urllib3\connection.py", line 181, in connect
    conn = self._new_conn()
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\urllib3\connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001F0737DEFC8>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\urllib3\util\retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='114.55.235.185', port=9031): Max retries exceeded with url: /autoyolConsole/main (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F0737DEFC8>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\tornado\web.py", line 1699, in _execute
    result = await result
  File "F:\MagicTestPlatform\apps\utils\wrappers.py", line 25, in wrapper
    await method(self, *args, **kwargs)
  File "F:\MagicTestPlatform\apps\interface_test\handlers.py", line 79, in post
    response = http_client.make_test_templates()
  File "F:\MagicTestPlatform\apps\utils\http_keywords.py", line 76, in make_test_templates
    response = self.post(**request_body)
  File "F:\MagicTestPlatform\apps\utils\http_keywords.py", line 27, in post
    return requests.post(verify=False, **kwargs)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\requests\api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='114.55.235.185', port=9031): Max retries exceeded with url: /autoyolConsole/main (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F0737DEFC8>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
[2019-12-03 23:00:39] [INFO] [MainThread] [handlers.py:44] Response Infomations:
+-----Headers-----+
| Content-Type    | text/plain      

Body:
| Traceback (most recent call last):
| 
[2019-12-03 23:00:39] [INFO] [MainThread] [handlers.py:63] Request Infomations:
+-----Headers-----+
| Host            | 127.0.0.1:8084  
| Connection      | keep-alive      
| Content-Length  | 113             
| Accept          | application/json, text/plain, */* 
| Origin          | http://localhost:8080 
| Authorization   | eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmlja19uYW1lIjpudWxsLCJleHAiOjE1NzUwMjI1MzJ9.pTzgTRDJHyQfEiLyRTxhcDf10FBCvG0_eyP1Wv0pPzY 
| User-Agent      | Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36 
| Content-Type    | application/json;charset=UTF-8 
| Sec-Fetch-Site  | cross-site      
| Sec-Fetch-Mode  | cors            
| Referer         | http://localhost:8080/interfacesManage 
| Accept-Encoding | gzip, deflate, br 
| Accept-Language | zh-CN,zh;q=0.9  
+----Arguments----+
| 'url'           | 'http://114.55.235.185:9031/autoyolConsole/main' 
| 'method'        | 'POST'          
| 'headers'       | '{}'            
| 'params'        | '{}'            
| 'project'       | 5               

