[2019-12-13 19:08:11] [INFO] [MainThread] [handlers.py:63] Request Infomations:
+-----Headers-----+
| Content-Type    | application/json 
| Authorization   | eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmlja19uYW1lIjpudWxsLCJleHAiOjE1NzYyMjI3NTR9.KdwdPYH43DI8Qt2bY08dEz5fUhB-lnD5S3NCS2iF4fo 
| User-Agent      | PostmanRuntime/7.20.1 
| Accept          | */*             
| Cache-Control   | no-cache        
| Postman-Token   | 4e78dc12-76b5-4022-80aa-2562a4b5ef03 
| Host            | 127.0.0.1:8084  
| Accept-Encoding | gzip, deflate   
| Content-Length  | 141             
| Connection      | keep-alive      
+----Arguments----+
| 'test_name'     | 'нч2221'         
| 'interfaces'    | [8, 9]          
| 'assertion'     | '12313'         
| 'db'            | 2               
| 'check_db'      | '123'           
| 'desc'          | '21q313132'     

[2019-12-13 19:08:11] [INFO] [MainThread] [handlers.py:44] Response Infomations:
+-----Headers-----+
| Content-Type    | application/json 

Body:
| TestCasesHandler object has list index out of range
