[2019-12-13 19:23:57] [INFO] [MainThread] [handlers.py:63] Request Infomations:
+-----Headers-----+
| Content-Type    | application/json 
| Authorization   | eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmlja19uYW1lIjpudWxsLCJleHAiOjE1NzYyMjI3NTR9.KdwdPYH43DI8Qt2bY08dEz5fUhB-lnD5S3NCS2iF4fo 
| User-Agent      | PostmanRuntime/7.20.1 
| Accept          | */*             
| Cache-Control   | no-cache        
| Postman-Token   | bd5e009c-4efb-4a35-aa33-72a30377f2c4 
| Host            | 127.0.0.1:8084  
| Accept-Encoding | gzip, deflate   
| Content-Length  | 141             
| Connection      | keep-alive      
+----Arguments----+
| 'test_name'     | 'нч2221'         
| 'interfaces'    | [8, 9]          
| 'assertion'     | '12313'         
| 'db'            | 2               
| 'check_db'      | '123'           
| 'desc'          | '21q313132'     

[2019-12-13 19:23:57] [ERROR] [MainThread] [handlers.py:105] Uncaught exception GET /cases/ (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8084', method='GET', uri='/cases/', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\tornado\web.py", line 1699, in _execute
    result = await result
  File "F:\MagicTestPlatform\common\core.py", line 37, in wrapper
    await method(self, *args, **kwargs)
  File "F:\MagicTestPlatform\apps\interface_test\handlers.py", line 260, in get
    interfaces_case_query = interfaces_case_query.filter(InterfacesTestCase.cases == index)
AttributeError: 'AsyncQueryWrapper' object has no attribute 'filter'
[2019-12-13 19:23:57] [INFO] [MainThread] [handlers.py:44] Response Infomations:
+-----Headers-----+
| Content-Type    | text/plain      

Body:
| Traceback (most recent call last):
| 
[2019-12-13 19:24:07] [INFO] [MainThread] [handlers.py:63] Request Infomations:
+-----Headers-----+
| Content-Type    | application/json 
| Authorization   | eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmlja19uYW1lIjpudWxsLCJleHAiOjE1NzYyMjI3NTR9.KdwdPYH43DI8Qt2bY08dEz5fUhB-lnD5S3NCS2iF4fo 
| User-Agent      | PostmanRuntime/7.20.1 
| Accept          | */*             
| Cache-Control   | no-cache        
| Postman-Token   | 75c0329d-99cb-4b93-af9d-1927e77f3671 
| Host            | 127.0.0.1:8084  
| Accept-Encoding | gzip, deflate   
| Content-Length  | 141             
| Connection      | keep-alive      
+----Arguments----+
| 'test_name'     | 'нч2221'         
| 'interfaces'    | [8, 9]          
| 'assertion'     | '12313'         
| 'db'            | 2               
| 'check_db'      | '123'           
| 'desc'          | '21q313132'     

[2019-12-13 19:24:07] [ERROR] [MainThread] [handlers.py:105] Uncaught exception GET /cases/ (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8084', method='GET', uri='/cases/', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\tornado\web.py", line 1699, in _execute
    result = await result
  File "F:\MagicTestPlatform\common\core.py", line 37, in wrapper
    await method(self, *args, **kwargs)
  File "F:\MagicTestPlatform\apps\interface_test\handlers.py", line 260, in get
    interfaces_case_query = interfaces_case_query.filter(InterfacesTestCase.cases == index)
AttributeError: 'AsyncQueryWrapper' object has no attribute 'filter'
[2019-12-13 19:24:07] [INFO] [MainThread] [handlers.py:44] Response Infomations:
+-----Headers-----+
| Content-Type    | text/plain      

Body:
| Traceback (most recent call last):
| 
