[2019-12-04 16:53:23] [INFO] [MainThread] [handlers.py:63] Request Infomations:
+-----Headers-----+
| Host            | 127.0.0.1:8084  
| Connection      | keep-alive      
| Access-Control-Request-Method | POST            
| Origin          | http://localhost:8080 
| User-Agent      | Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36 
| Access-Control-Request-Headers | authorization,content-type 
| Accept          | */*             
| Sec-Fetch-Site  | cross-site      
| Sec-Fetch-Mode  | cors            
| Referer         | http://localhost:8080/interfacesManage 
| Accept-Encoding | gzip, deflate, br 
| Accept-Language | zh-CN,zh;q=0.9  

[2019-12-04 16:53:23] [INFO] [MainThread] [handlers.py:44] Response Infomations:
+-----Headers-----+
| Content-Type    | application/json 

Body:
| InterfacesDebugHandler object has list index out of range
[2019-12-04 16:53:23] [INFO] [MainThread] [handlers.py:63] Request Infomations:
+-----Headers-----+
| Host            | 127.0.0.1:8084  
| Connection      | keep-alive      
| Content-Length  | 579             
| Accept          | application/json, text/plain, */* 
| Origin          | http://localhost:8080 
| Authorization   | eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmlja19uYW1lIjpudWxsLCJleHAiOjE1NzUwMjI1MzJ9.pTzgTRDJHyQfEiLyRTxhcDf10FBCvG0_eyP1Wv0pPzY 
| User-Agent      | Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36 
| Content-Type    | application/json;charset=UTF-8 
| Sec-Fetch-Site  | cross-site      
| Sec-Fetch-Mode  | cors            
| Referer         | http://localhost:8080/interfacesManage 
| Accept-Encoding | gzip, deflate, br 
| Accept-Language | zh-CN,zh;q=0.9  
+----Arguments----+
| 'url'           | 'v5121/homePop/getPop' 
| 'method'        | 'get'           
| 'headers'       | '{"Accept":"application/json;version=3.0;compress=false"}' 
| 'params'        | 'cityCode=310100&isRenter=1&token=2a3b3ad3e4404281a78d841eabccef46&OS=ANDROID&OsVersion=28&AppVersion=107&IMEI=869704033142271&mac=9CE82B30746D&androidID=f6eb3bbd8b43d0cb&PublicLongitude=121.409381&PublicLatitude=31.172141&publicCityCode=021&appName=atzucheApp&deviceName=vivoX21A&publicToken=2a3b3ad3e4404281a78d841eabccef46&AppChannelId=testmarket&AndroidId=f6eb3bbd8b43d0cb&requestId=9CE82B30746D1574843951903&mem_no=494671888&schema=B' 
| 'project'       | 5               

[2019-12-04 16:53:23] [INFO] [MainThread] [handlers.py:44] Response Infomations:
+-----Headers-----+
| Content-Type    | application/json 

Body:
| {
|     "code": 1,
|     "msg": "接口请求成功",
|     "data": {
|         "status_code": 200,
|         "times": 0.26,
|         "response_body": "{\"data\":null,\"resCode\":\"900005\",\"resMsg\":\"无效请求\"}{\"data\":null,\"resCode\":\"900001\",\"resMsg\":\"客户端版本过低,请及时更新\"}"
|     }
| }
[2019-12-04 16:53:23] [INFO] [MainThread] [handlers.py:63] Request Infomations:
+-----Headers-----+
| Host            | 127.0.0.1:8084  
| Connection      | keep-alive      
| Content-Length  | 579             
| Accept          | application/json, text/plain, */* 
| Origin          | http://localhost:8080 
| Authorization   | eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmlja19uYW1lIjpudWxsLCJleHAiOjE1NzUwMjI1MzJ9.pTzgTRDJHyQfEiLyRTxhcDf10FBCvG0_eyP1Wv0pPzY 
| User-Agent      | Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36 
| Content-Type    | application/json;charset=UTF-8 
| Sec-Fetch-Site  | cross-site      
| Sec-Fetch-Mode  | cors            
| Referer         | http://localhost:8080/interfacesManage 
| Accept-Encoding | gzip, deflate, br 
| Accept-Language | zh-CN,zh;q=0.9  
+----Arguments----+
| 'url'           | 'v5121/homePop/getPop' 
| 'method'        | 'get'           
| 'headers'       | '{"Accept":"application/json;version=3.0;compress=false"}' 
| 'params'        | 'cityCode=310100&isRenter=1&token=2a3b3ad3e4404281a78d841eabccef46&OS=ANDROID&OsVersion=28&AppVersion=107&IMEI=869704033142271&mac=9CE82B30746D&androidID=f6eb3bbd8b43d0cb&PublicLongitude=121.409381&PublicLatitude=31.172141&publicCityCode=021&appName=atzucheApp&deviceName=vivoX21A&publicToken=2a3b3ad3e4404281a78d841eabccef46&AppChannelId=testmarket&AndroidId=f6eb3bbd8b43d0cb&requestId=9CE82B30746D1574843951903&mem_no=494671888&schema=B' 
| 'project'       | 5               

[2019-12-04 16:53:23] [INFO] [MainThread] [handlers.py:44] Response Infomations:
+-----Headers-----+
| Content-Type    | application/json 

Body:
| {
|     "code": 1,
|     "msg": "接口请求成功",
|     "data": {
|         "status_code": 200,
|         "times": 0.08,
|         "response_body": "{\"data\":null,\"resCode\":\"900005\",\"resMsg\":\"无效请求\"}{\"data\":null,\"resCode\":\"900001\",\"resMsg\":\"客户端版本过低,请及时更新\"}"
|     }
| }
[2019-12-04 16:53:29] [INFO] [MainThread] [handlers.py:63] Request Infomations:
+-----Headers-----+
| Host            | 127.0.0.1:8084  
| Connection      | keep-alive      
| Content-Length  | 619             
| Accept          | application/json, text/plain, */* 
| Origin          | http://localhost:8080 
| Authorization   | eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmlja19uYW1lIjpudWxsLCJleHAiOjE1NzUwMjI1MzJ9.pTzgTRDJHyQfEiLyRTxhcDf10FBCvG0_eyP1Wv0pPzY 
| User-Agent      | Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36 
| Content-Type    | application/json;charset=UTF-8 
| Sec-Fetch-Site  | cross-site      
| Sec-Fetch-Mode  | cors            
| Referer         | http://localhost:8080/interfacesManage 
| Accept-Encoding | gzip, deflate, br 
| Accept-Language | zh-CN,zh;q=0.9  
+----Arguments----+
| 'url'           | 'v5121/homePop/getPop' 
| 'interface_name' | 'v5121/homePop/getPop' 
| 'method'        | 'get'           
| 'headers'       | '{"Accept":"application/json;version=3.0;compress=false"}' 
| 'params'        | 'cityCode=310100&isRenter=1&token=2a3b3ad3e4404281a78d841eabccef46&OS=ANDROID&OsVersion=28&AppVersion=107&IMEI=869704033142271&mac=9CE82B30746D&androidID=f6eb3bbd8b43d0cb&PublicLongitude=121.409381&PublicLatitude=31.172141&publicCityCode=021&appName=atzucheApp&deviceName=vivoX21A&publicToken=2a3b3ad3e4404281a78d841eabccef46&AppChannelId=testmarket&AndroidId=f6eb3bbd8b43d0cb&requestId=9CE82B30746D1574843951903&mem_no=494671888&schema=B' 
| 'project'       | 5               

[2019-12-04 16:53:29] [ERROR] [MainThread] [handlers.py:105] Uncaught exception POST /interfaces/ (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8084', method='POST', uri='/interfaces/', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee_async.py", line 170, in get
    return list(result)[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\MagicTestPlatform\apps\interface_test\handlers.py", line 130, in post
    Interfaces, interface_name=form.interface_name.data
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee_async.py", line 172, in get
    raise model.DoesNotExist
apps.interface_test.models.InterfacesDoesNotExist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee_async.py", line 1540, in _run_sql
    yield from cursor.execute(operation, *args, **kwargs)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\aiomysql\cursors.py", line 239, in execute
    await self._query(query)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\aiomysql\cursors.py", line 457, in _query
    await conn.query(q)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\aiomysql\connection.py", line 428, in query
    await self._read_query_result(unbuffered=unbuffered)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\aiomysql\connection.py", line 622, in _read_query_result
    await result.read()
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\aiomysql\connection.py", line 1105, in read
    first_packet = await self.connection._read_packet()
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\aiomysql\connection.py", line 593, in _read_packet
    packet.check_error()
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.DataError: (1406, "Data too long for column 'params' at row 1")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\tornado\web.py", line 1699, in _execute
    result = await result
  File "F:\MagicTestPlatform\apps\utils\wrappers.py", line 25, in wrapper
    await method(self, *args, **kwargs)
  File "F:\MagicTestPlatform\apps\interface_test\handlers.py", line 144, in post
    creator=self.current_user
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee_async.py", line 181, in create
    pk = yield from self.execute(query)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee_async.py", line 269, in execute
    return (yield from execute(query))
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee_async.py", line 433, in execute
    return (yield from coroutine(query))
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee_async.py", line 597, in insert
    cursor = yield from _execute_query_async(query)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee_async.py", line 1558, in _execute_query_async
    return (yield from _run_sql(query.database, *query.sql()))
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee_async.py", line 1545, in _run_sql
    return cursor
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 3656, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 135, in reraise
    raise value.with_traceback(tb)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee_async.py", line 1540, in _run_sql
    yield from cursor.execute(operation, *args, **kwargs)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\aiomysql\cursors.py", line 239, in execute
    await self._query(query)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\aiomysql\cursors.py", line 457, in _query
    await conn.query(q)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\aiomysql\connection.py", line 428, in query
    await self._read_query_result(unbuffered=unbuffered)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\aiomysql\connection.py", line 622, in _read_query_result
    await result.read()
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\aiomysql\connection.py", line 1105, in read
    first_packet = await self.connection._read_packet()
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\aiomysql\connection.py", line 593, in _read_packet
    packet.check_error()
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
peewee.DataError: (1406, "Data too long for column 'params' at row 1")
[2019-12-04 16:53:29] [INFO] [MainThread] [handlers.py:44] Response Infomations:
+-----Headers-----+
| Content-Type    | text/plain      

Body:
| Traceback (most recent call last):
| 
